server:
  servlet:
    context-path: /api
  shutdown: GRACEFUL
  forward-headers-strategy: NATIVE


application:
  auto-id:
    start: 100
  message.default-value: ${MESSAGE_DEFAULT}


spring:
  jackson:
    default-property-inclusion: NON_NULL
